# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 05:22
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170331_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.wagtailcore.fields.StreamField((('text_content', wagtail.wagtailcore.blocks.RichTextBlock(icon='pilcrow')), ('image', wagtail.wagtailcore.blocks.StructBlock((('image', wagtail.wagtailimages.blocks.ImageChooserBlock()), ('caption', wagtail.wagtailcore.blocks.RichTextBlock()), ('alt', wagtail.wagtailcore.blocks.CharBlock())), icon='image', label='Image')), ('code', wagtail.wagtailcore.blocks.StructBlock((('code', wagtail.wagtailcore.blocks.TextBlock(icon='pilcrow')), ('language', wagtail.wagtailcore.blocks.CharBlock())), icon='code', label='Code')), ('raw_html', wagtail.wagtailcore.blocks.RawHTMLBlock(label='Raw HTML')))),
        ),
    ]
