# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('blogpage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPage')),
                ('project_date', models.DateField(verbose_name='Project Date')),
            ],
            options={
                'abstract': False,
            },
            bases=('blog.blogpage',),
        ),
    ]
