# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolioindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliopage',
            name='priority',
            field=models.SmallIntegerField(default=1, unique='true', verbose_name='Priority'),
            preserve_default=False,
        ),
    ]
